version: '3'

services:
  postgres:
    image: postgres:10-alpine
    restart: always
    hostname: postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    expose:
      - ${POSTGRES_PORT:-5432}
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
    volumes:
      - ./database/data:/var/lib/postgresql/data
