FROM node:12-alpine

RUN apk update && apk add --no-cache unzip openjdk11-jre-headless git

WORKDIR /home/node/epub-checker

RUN chown -R node:node /home/node/epub-checker

USER node

COPY --chown=node:node package.json ./package.json
COPY --chown=node:node yarn.lock ./yarn.lock

RUN yarn

COPY --chown=node:node . .

RUN chmod +x ./scripts/wait-for-it.sh

ENTRYPOINT . scripts/startServer.sh
