version: '2'

services:
  server:
    depends_on:
      - "db"
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports: 
      - ${SERVER_PORT:-3000}:3000
    environment:
      - PUBSWEET_SECRET=${PUBSWEET_SECRET:-dev_secret}
      - POSTGRES_USER=${POSTGRES_USER:-dev}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secretpassword}
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB:-editoria_dev}
      - POSTGRES_PORT=5432
      - SERVER_PORT=3000
      - NODE_ENV=${NODE_ENV:-development}
  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
    # volumes:
    #   - ./database/data:/var/lib/postgresql/data
